name: healthy_food
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.0
  another_flutter_splash_screen: ^1.1.5
  awesome_notifications: ^0.8.2
  bloc: ^8.1.2
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_custom_clippers: ^2.1.0
  flutter_hooks: ^0.20.3
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.0.1
  flutter_native_splash: ^2.3.6
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  intl: ^0.18.1
  ionicons: ^0.2.2
  latlong2: ^0.9.0
  lottie: ^2.7.0
  molten_navigationbar_flutter: ^1.0.1
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0+1
  timelines: ^0.1.0
  url_launcher: ^6.2.1
  uuid: ^4.2.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Healthy Slogan.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/Healthy Slogan.png"
    icon_size: 48

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 500
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 900
flutter_intl:
  enabled: true
