// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3dZaZ8wCZC0k-hITc5QeARCXgTrjsfZE',
    appId: '1:651269676503:web:cd0c6e53cf86dc23353f92',
    messagingSenderId: '651269676503',
    projectId: 'massege-c61d0',
    authDomain: 'massege-c61d0.firebaseapp.com',
    databaseURL: 'https://massege-c61d0-default-rtdb.firebaseio.com',
    storageBucket: 'massege-c61d0.appspot.com',
    measurementId: 'G-RG764EQ5PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBob3iHoe4fyEZ1Xey-pBP1nkxit2wcL5k',
    appId: '1:651269676503:android:b6c279a396cf6bfa353f92',
    messagingSenderId: '651269676503',
    projectId: 'massege-c61d0',
    databaseURL: 'https://massege-c61d0-default-rtdb.firebaseio.com',
    storageBucket: 'massege-c61d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8z-7E9zztyweNleSLQSvu6BE9WFgMlyk',
    appId: '1:651269676503:ios:775ad3803f6fdd7a353f92',
    messagingSenderId: '651269676503',
    projectId: 'massege-c61d0',
    databaseURL: 'https://massege-c61d0-default-rtdb.firebaseio.com',
    storageBucket: 'massege-c61d0.appspot.com',
    iosBundleId: 'com.example.healthyFood',
  );
}
